### ISSUE TITLE
cannot find symbol import androidx.annotation.Nullable

### ISSUE THREAD

**Issue by rdgomt** [rmrs/react-native-settings#41]
## Issue

![error](https://user-images.githubusercontent.com/23437436/71645117-05b88100-2cb2-11ea-90b6-cc1fe1520cfb.png)

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

React Native 0.59.10

![info](https://user-images.githubusercontent.com/23437436/71645136-54661b00-2cb2-11ea-8aa8-9594df6e29ec.png)

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android

</p>
</details>

**Comment by rdgomt** [comment]
Working fine with react-native-settings@0.1.1

**Comment by erezrokah** [comment]
Hi @rdgomt sorry for the late reply, can you share a repo reproducing this issue? We have a working example in this repo, but it is `react-native 0.60.4`. Also did you try [this solution](https://github.com/facebook/react-native-fbsdk/issues/600#issuecomment-524674288)?

**Comment by rdgomt** [comment]
Hi! Don't worry, I'll be using @0.1.1 until I update React Native. AndroidX is being a head pain for now.

**Comment by manawaraquevix** [comment]
change import line as
`import android.support.annotation.Nullable;`
